githubConfigSecret:
  github_token: ""
githubConfigUrl: "https://github.com/xxx"
template:
  spec:
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      volumeMounts:
      - name: work-volume
        mountPath: /runner/_work
    
    volumes:
    - name: work-volume
      persistentVolumeClaim:
        claimName: runner-work-pvc  # Matches PVC name
